# Generated by Django 4.1.4 on 2023-01-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('jurisdiction', models.CharField(max_length=2)),
                ('court', models.CharField(max_length=10)),
                ('canlii_citation', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('style_of_cause', models.CharField(max_length=200)),
                ('docket_number', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('mcgill_citation', models.CharField(max_length=200)),
            ],
        ),
    ]
