# Generated by Django 3.2.12 on 2023-01-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_citation_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanLIIURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('times_inputted', models.IntegerField()),
                ('ip_address', models.CharField(max_length=200)),
                ('user_jurisdiction', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='jurisdiction',
            new_name='case_jurisdiction',
        ),
    ]
