# Generated by Django 3.2.12 on 2023-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230112_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='case_jurisdiction',
            field=models.CharField(choices=[('CA', 'Canada'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('SK', 'Saskatchewan'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('PE', 'Prince Edward Island'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=2),
        ),
    ]
