# Generated by Django 3.2.12 on 2023-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_citation_citation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='case_id',
            new_name='caseId',
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='docket_number',
            new_name='docketNumber',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='date',
        ),
        migrations.AddField(
            model_name='citation',
            name='decisionDate',
            field=models.CharField(default='2022-01-22', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
