# Generated by Django 3.2.12 on 2023-01-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230122_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='database_id',
            new_name='databaseId',
        ),
    ]
