# Generated by Django 3.2.12 on 2023-02-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_database_id_citation_databaseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='times_inputted',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user_jurisdiction',
        ),
    ]
