# Generated by Django 3.2.12 on 2023-01-08 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230107_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=10)),
                ('changelog', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'changelogs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['date'], name='app_changel_date_813915_idx'),
        ),
    ]
