# Generated by Django 3.2.12 on 2023-01-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230108_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanLIIURL',
            new_name='Submission',
        ),
    ]
