# Generated by Django 3.2.12 on 2023-01-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_canliiurl_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='mcgill_citation',
        ),
        migrations.AddField(
            model_name='citation',
            name='short_url',
            field=models.URLField(default='http://sample.url'),
            preserve_default=False,
        ),
    ]
