# Generated by Django 3.2.12 on 2023-01-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_citation_database_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='mcgill_citation',
            field=models.CharField(default='dd', max_length=200),
            preserve_default=False,
        ),
    ]
