# Generated by Django 3.2.12 on 2023-01-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_citation_mcgill_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='database_citation',
            field=models.CharField(default='dd', max_length=200),
            preserve_default=False,
        ),
    ]
