# Generated by Django 3.2.12 on 2023-01-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_citation_database_citation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='style_of_cause',
            new_name='title',
        ),
    ]
