# Generated by Django 3.2.12 on 2023-01-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230115_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='citation',
            field=models.CharField(default='dd', max_length=200),
            preserve_default=False,
        ),
    ]
